"""create_evidences_document_requests_traffic_reports

Revision ID: 86aa3d1ad317
Revises: f18bfb81129a
Create Date: 2026-06-01 16:55:58.511394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86aa3d1ad317'
down_revision: Union[str, None] = 'f18bfb81129a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'WAIVED', name='documentrequeststatus'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_requests_tenant_claim', 'document_requests', ['tenant_id', 'claim_id'], unique=False)
    op.create_index('ix_doc_requests_tenant_status', 'document_requests', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_document_requests_tenant_id'), 'document_requests', ['tenant_id'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_request_id', sa.Uuid(), nullable=True),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('PHOTO', 'VIDEO', 'INVOICE', 'TECHNICAL_REPORT', 'SKETCH', 'POLICE_REPORT', 'PERSONAL_DOC', 'OTHER', name='evidencetype'), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False, comment='S3 key'),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Peritaje fields, EXIF, OCR, etc.'),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('document_request_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('claim_request_id IS NOT NULL OR claim_id IS NOT NULL', name='ck_evidences_subject_must_exist'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['claim_request_id'], ['claim_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_request_id'], ['document_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidences_tenant_claim', 'evidences', ['tenant_id', 'claim_id'], unique=False)
    op.create_index('ix_evidences_tenant_doc_request', 'evidences', ['tenant_id', 'document_request_id'], unique=False)
    op.create_index(op.f('ix_evidences_tenant_id'), 'evidences', ['tenant_id'], unique=False)
    op.create_index('ix_evidences_tenant_request', 'evidences', ['tenant_id', 'claim_request_id'], unique=False)
    op.create_table('traffic_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True, comment='Archivo del acta subido como evidencia (type=police_report)'),
    sa.Column('officer_name', sa.String(length=300), nullable=True),
    sa.Column('report_code', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=200), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_traffic_reports_tenant_claim', 'traffic_reports', ['tenant_id', 'claim_id'], unique=False)
    op.create_index(op.f('ix_traffic_reports_tenant_id'), 'traffic_reports', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_traffic_reports_tenant_id'), table_name='traffic_reports')
    op.drop_index('ix_traffic_reports_tenant_claim', table_name='traffic_reports')
    op.drop_table('traffic_reports')
    op.drop_index('ix_evidences_tenant_request', table_name='evidences')
    op.drop_index(op.f('ix_evidences_tenant_id'), table_name='evidences')
    op.drop_index('ix_evidences_tenant_doc_request', table_name='evidences')
    op.drop_index('ix_evidences_tenant_claim', table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_document_requests_tenant_id'), table_name='document_requests')
    op.drop_index('ix_doc_requests_tenant_status', table_name='document_requests')
    op.drop_index('ix_doc_requests_tenant_claim', table_name='document_requests')
    op.drop_table('document_requests')
    # ### end Alembic commands ###
