"""create_notifications

Revision ID: e0fb442c7e1e
Revises: b2f9c1d8e3a4
Create Date: 2026-06-02 22:11:05.375809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0fb442c7e1e'
down_revision: Union[str, None] = 'b2f9c1d8e3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_account_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('intake_rejected', 'docs_requested', 'escalated', 'assigned', 'decision', 'state_change', 'claim_created', name='notificationkind'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_tenant_account', 'notifications', ['tenant_id', 'recipient_account_id'], unique=False)
    op.create_index('ix_notifications_tenant_entity', 'notifications', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_tenant_recipient', 'notifications', ['tenant_id', 'recipient_user_id'], unique=False)
    op.create_index('ix_claim_requests_tenant_status', 'claim_requests', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_claims_tenant_status', 'claims', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_claims_tenant_status', table_name='claims')
    op.drop_index('ix_claim_requests_tenant_status', table_name='claim_requests')
    op.drop_index('ix_notifications_tenant_recipient', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('ix_notifications_tenant_entity', table_name='notifications')
    op.drop_index('ix_notifications_tenant_account', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
