"""create_claim_tables

Revision ID: f18bfb81129a
Revises: c3d4e5f6a7b8
Create Date: 2026-05-30 21:27:36.723418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f18bfb81129a'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('state_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_type', sa.Enum('CLAIM_REQUEST', 'CLAIM', name='subjecttype'), nullable=False),
    sa.Column('subject_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=2000), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_state_transitions_subject', 'state_transitions', ['tenant_id', 'subject_type', 'subject_id'], unique=False)
    op.create_index(op.f('ix_state_transitions_tenant_id'), 'state_transitions', ['tenant_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_number', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_INTAKE_REVIEW', 'FORMALIZED', 'REJECTED_AT_INTAKE', name='claimrequeststatus'), nullable=False),
    sa.Column('policyholder_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('accident_date', sa.Date(), nullable=True),
    sa.Column('accident_time', sa.Time(), nullable=True),
    sa.Column('accident_location', sa.String(length=500), nullable=True),
    sa.Column('accident_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accident_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accident_description', sa.Text(), nullable=True),
    sa.Column('reported_damages', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('intake_decision_reason', sa.Text(), nullable=True),
    sa.Column('formalized_claim_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['formalized_claim_id'], ['claims.id'], ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policyholder_id'], ['policyholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_requests_tenant_id'), 'claim_requests', ['tenant_id'], unique=False)
    op.create_index('ix_claim_requests_tenant_number', 'claim_requests', ['tenant_id', 'request_number'], unique=True)
    op.create_index('ix_claim_requests_tenant_status', 'claim_requests', ['tenant_id', 'status'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_number', sa.String(length=30), nullable=False),
    sa.Column('claim_request_id', sa.Uuid(), nullable=True),
    sa.Column('policyholder_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'IN_REVIEW', 'OBSERVED', 'DOCS_PENDING', 'IN_EVALUATION', 'APPROVED', 'REJECTED', 'CLOSED', name='claimstatus'), nullable=False),
    sa.Column('source', sa.Enum('MOBILE_APP', 'INTERNAL', name='claimsource'), nullable=False),
    sa.Column('accident_date', sa.Date(), nullable=False),
    sa.Column('accident_time', sa.Time(), nullable=True),
    sa.Column('accident_location', sa.String(length=500), nullable=False),
    sa.Column('accident_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accident_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accident_description', sa.Text(), nullable=True),
    sa.Column('reported_damages', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_analyst_id', sa.Uuid(), nullable=True),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='claimdecision'), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_analyst_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_request_id'], ['claim_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policyholder_id'], ['policyholders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_request_id')
    )
    op.create_index('ix_claims_tenant_analyst', 'claims', ['tenant_id', 'assigned_analyst_id'], unique=False)
    op.create_index(op.f('ix_claims_tenant_id'), 'claims', ['tenant_id'], unique=False)
    op.create_index('ix_claims_tenant_number', 'claims', ['tenant_id', 'claim_number'], unique=True)
    op.create_index('ix_claims_tenant_status', 'claims', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_claims_tenant_supervisor', 'claims', ['tenant_id', 'supervisor_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_observations_tenant_claim', 'observations', ['tenant_id', 'claim_id'], unique=False)
    op.create_index(op.f('ix_observations_tenant_id'), 'observations', ['tenant_id'], unique=False)
    op.create_table('third_parties',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('DRIVER', 'WITNESS', 'VICTIM', 'VEHICLE_OWNER', name='thirdpartykind'), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('document_id', sa.String(length=20), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_info', sa.String(length=200), nullable=True),
    sa.Column('statement', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_third_parties_tenant_claim', 'third_parties', ['tenant_id', 'claim_id'], unique=False)
    op.create_index(op.f('ix_third_parties_tenant_id'), 'third_parties', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_parties_tenant_id'), table_name='third_parties')
    op.drop_index('ix_third_parties_tenant_claim', table_name='third_parties')
    op.drop_table('third_parties')
    op.drop_index(op.f('ix_observations_tenant_id'), table_name='observations')
    op.drop_index('ix_observations_tenant_claim', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_claims_tenant_supervisor', table_name='claims')
    op.drop_index('ix_claims_tenant_status', table_name='claims')
    op.drop_index('ix_claims_tenant_number', table_name='claims')
    op.drop_index(op.f('ix_claims_tenant_id'), table_name='claims')
    op.drop_index('ix_claims_tenant_analyst', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_claim_requests_tenant_status', table_name='claim_requests')
    op.drop_index('ix_claim_requests_tenant_number', table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_tenant_id'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_state_transitions_tenant_id'), table_name='state_transitions')
    op.drop_index('ix_state_transitions_subject', table_name='state_transitions')
    op.drop_table('state_transitions')
    # ### end Alembic commands ###
